language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head
  - rbx
  - jruby

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
    - rvm: ruby-head

before_install: gem install bundler -v 1.12.5

